server:
  port: ${PGATE_SERVER_PORT:80}
  servlet:
    context-path: /
spring:
  application:
    name: payment-gateway
  datasource:
    username: ${PGATE_SVC_DB_USERNAME:sa}
    password: ${PGATE_SVC_DB_PASSWORD:sa}
    url: ${PGATE_SVC_DB_URL:jdbc:h2:mem:dbGateway}
    driver-class-name: ${PGATE_SVC_DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${PGATE_SVC_DB_DIALECT:org.hibernate.dialect.H2Dialect}
        show-sql: true
        hbm2ddl:
          auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service/eureka}
  instance:
    preferIpAddress: true

waya:
  wallet:
    auth: AUTHENTICATION-SERVICE
    authurl: https://services.staging.wayabank.ng/auth-service/api/v1
    tempname: WALLET-SERVICE
    tempurl: https://services.staging.wayabank.ng/temporal-service/api/v1
  application:
    payment-gateway-mode: ${PAYMENT_GATEWAY_MODE:TEST}
  notification-service:
    baseurl: https://services.staging.wayabank.ng/notification-service
  logging-service:
    base-url: https://services.staging.wayabank.ng/logs-service
  qrcode:
    name: QRCODE-SERVICE
    baseurl: https://services.staging.wayabank.ng/qrcode-service/api/v1
  unified-payment:
    name: unified-payment
    baseurl: https://test.payarena.com
    merchant: FAVE
    secret: 82A60EE5FBB2B5309166A0ADF60B5FE1E445AB9A2EB35C0D
  callback:
    baseurl: https://services.staging.wayabank.ng/payment-gateway/api/v1/wayaCallBack
  formcallback:
    baseurl: https://services.staging.wayabank.ng/payment-gateway/waya/callback
  identitymanager:
    name: IDENTITYMANAGER-SERVICE
    url: https://services.staging.wayabank.ng/identity-manager-service/api/v1

service:
  name: ${SERVICE_NAME:tbaadm@wayapaychat.com}
  pass: ${SERVICE_PASS:fintemp@#123}
  encrypt-all-merchant-secretkey-with: S@$@@@@@!!!!!ads#$%#$@#!#$@$@545345fdsdf@@$353^^*(*@#$%#@$%#$@#@#$%#%#@
  thirdparty:
    unified-payment:
      callback:
        accepted-origins:service: { "https://acce" }