package com.wayapaychat.paymentgateway.enumm;

public enum Permit {

    VIEW_WEB_POS_METRICS_S, VIEW_TERMINAL_POS_METRICS_S, VIEW_WEB_POS_TRANSACTION_S,
    EXPORT_WEB_POS_TRANSACTION_S, MANAGE_REFUNDS_WEB_POS_S, VIEW_TERMINAL_POS_TRANSACTION_S,
    EXPORT_TERMINAL_POS_TRANSACTION_S, MANAGE_REFUNDS_WEB_TERMINAL_S, VIEW_CUSTOMERS_S, CREATE_CUSTOMERS_S,
    UPDATE_CUSTOMERS_S, VIEW_CUSTOMERS_INSIGHTS_S, VIEW_WEB_POS_SETTLEMENTS_S, EXPORT_POS_SETTLEMENTS_S,
    VIEW_TERMINAL_POS_SETTLEMENTS_S, EXPORT_TERMINAL_POS_SETTLEMENTS_S,

    VIEW_PAYMENT_LINK_S, CREATE_PAYMENT_LINK_S, UPDATE_PAYMENT_LINKS_S, DELETE_PAYMENT_LINK_S,
    VIEW_SUBSCRIPTIONS_S, CREATE_SUBSCRIPTIONS_S, VIEW_TERMINAL_POS_S, UPDATE_SUBSCRIPTIONS_S,
    CREATE_PLANS_S, VIEW_PLANS_S, UPDATE_PLANS_S, DELETE_PLANS_S,
    VIEW_CUSTOMERS_SUBSCRIPTION_S, UPDATE_CUSTOMERS_SUBSCRIPTION_S, DELETE_CUSTOMERS_SUBSCRIPTION_S, CREATE_CUSTOMERS_SUBSCRIPTION_S,

    VIEW_WEB_POS_METRICS, VIEW_TERMINAL_POS_METRICS, VIEW_WEB_POS_TRANSACTION, EXPORT_WEB_POS_TRANSACTION,
    MANAGE_REFUNDS_WEB_POS, VIEW_TERMINAL_POS_TRANSACTION, EXPORT_TERMINAL_POS_TRANSACTION, MANAGE_REFUNDS_WEB_TERMINAL,
    VIEW_CUSTOMERS_INSIGHTS, VIEW_WEB_POS_SETTLEMENTS, EXPORT_POS_SETTLEMENTS, VIEW_TERMINAL_POS_SETTLEMENTS, EXPORT_TERMINAL_POS_SETTLEMENTS,

    VIEW_CUSTOMERS_SUBSCRIPTION, UPDATE_CUSTOMERS_SUBSCRIPTION, DELETE_CUSTOMERS_SUBSCRIPTION, CREATE_CUSTOMERS_SUBSCRIPTION,
    CREATE_PLANS, VIEW_PLANS, UPDATE_PLANS, DELETE_PLANS,
    VIEW_SUBSCRIPTIONS, CREATE_SUBSCRIPTIONS, UPDATE_SUBSCRIPTIONS, DELETE_SUBSCRIPTIONS, DELETE_SUBSCRIPTIONS_S,
    VIEW_CUSTOMERS, CREATE_CUSTOMERS, UPDATE_CUSTOMERS, DELETE_CUSTOMERS,
    CREATE_PAYMENT_LINKS, UPDATE_PAYMENT_LINKS, DELETE_PAYMENT_LINKS, VIEW_PAYMENT_LINKS,

    APP_ADMIN, LOCK_USER, CREATE_USER, DELETE_USER, UPDATE_USER, READ_USER, UNLOCK_USER,APP_MERCHANT, APP_AGENT, APP_AGGREGATOR,APP_SUPER_ADMIN,
    APP_OWNER,
    SETTLEMENTS, UPDATE_SETTLEMENT_PRICING
}