package com.wayapaychat.paymentgateway.enumm;

public enum Role {
    ROLE_ADMIN_OWNER,
    ROLE_ADMIN_SUPER,
    ROLE_ADMIN_INITIATOR,
    ROLE_ADMIN_APPROVAL,
    ROLE_ADMIN_REPORT,
    ROLE_ADMIN_APP,
    ROLE_ADMIN_THIRD_PARTY,
    ROLE_USER_ADMIN,
    ROLE_USER_SUPPORT,
    ROLE_USER_FINANCE,
    ROLE_USER_DEVELOPER,
    ROLE_USER_MERCHANT,
    ROLE_USER_AGENT,
    ROLE_USER_AGGREGATOR,
    
    ROLE_ANONYMOUS,
    METRICS, TRANSACTIONS, CUSTOMERS, SUBSCRIPTIONS,
    PAYMENT_LINK, PLANS_SUB, TERMINAL_POS, CUSTOMERS_SUBSCRIPTION,
    SUPER_ADMIN, ADMIN, OWNER,ROLE_CUSTOMER, ROLE_PLAN, ROLE_SUBSCRIPTION, ROLE_CUSTOMER_SUBSCRIPTION, ROLE_PAYMENT_LINK,
    ROLE_OWNER_ADMIN, ROLE_SUPER_ADMIN, ROLE_APP_ADMIN, ROLE_CORP_ADMIN, ROLE_CORP, ROLE_USER, ROLE_AGENT, ROLE_APPROVAL,
    ROLE_MERCHANT, ROLE_REVIEWER, ROLE_USER_OWNER;
}
