package com.wayapaychat.paymentgateway.enumm;

public enum Role {
    METRICS, TRANSACTIONS, CUSTOMERS, SUBSCRIPTIONS,
    PAYMENT_LINK, PLANS_SUB, TERMINAL_POS, CUSTOMERS_SUBSCRIPTION,
    SUPER_ADMIN, ADMIN, OWNER,ROLE_CUSTOMER, ROLE_PLAN, ROLE_SUBSCRIPTION, ROLE_CUSTOMER_SUBSCRIPTION, ROLE_PAYMENT_LINK,
    ROLE_OWNER_ADMIN, ROLE_SUPER_ADMIN, ROLE_APP_ADMIN, ROLE_CORP_ADMIN, ROLE_CORP, ROLE_USER, ROLE_APPROVAL,
    ROLE_MERCHANT;
}
