package com.wayapaychat.paymentgateway.enumm;

public enum TransactionStatus {
    CANCELLED, FAILED, SUCCESSFUL, ERROR, ABANDONED, EXPIRED, PENDING,
    APPROVED, REJECTED, DECLINED, INITIATED, TIMEOUT,REFUNDED,
    SYSTEM_ERROR,BANK_ERROR,CUSTOMER_ERROR,FRAUD_ERROR
}
