package com.wayapaychat.paymentgateway.enumm;

public enum TransactionStatus {
	TRANSACTION_NOT_PROCESSED,TRANSACTION_PENDING, TRANSACTION_EXPIRED, TRANSACTION_ERROR,
	TRANSACTION_REFUNDED,TRANSACTION_CANCELLED,TRANSACTION_FAILED,TRANSACTION_COMPLETED,
	TRANSACTION_ABANDON,REFUNDED,CANCELLED,FAILED,SUCCESSFUL,ERROR,ABANDONED,EXPIRED,PENDING,
	APPROVED, REJECTED,DECLINED, INITIATED,TIMEOUT
}
